import type { ProductTourStep } from "./productTour.types"

export const productTourSteps: ProductTourStep[] = [
  {
    id: "welcome",
    path: "/dashboard",
    eyebrow: "Welcome",
    title: "Your AI visibility command center",
    body: "This workspace shows where your brand appears across AI answers, why it appears, and what to improve next.",
    placement: "center",
  },
  {
    id: "workspace",
    path: "/dashboard",
    targetId: "workspace-switcher",
    eyebrow: "Project",
    title: "Start with the brand workspace",
    body: "Switch between tracked brands here. Every score, prompt, source, and recommendation updates around the selected project.",
    placement: "right",
  },
  {
    id: "filters",
    path: "/dashboard",
    targetId: "top-filters",
    eyebrow: "Controls",
    title: "Slice the evidence before you act",
    body: "Use time range, topic, and model filters to inspect exactly which answers changed and export clean reports when needed.",
    placement: "bottom",
  },
  {
    id: "scorecards",
    path: "/dashboard",
    targetId: "overview-scorecards",
    eyebrow: "Overview",
    title: "Read the four signals first",
    body: "Visibility tells if AI mentions you, Position shows where you rank, Sentiment tracks tone, and Sources reveals citation strength.",
    placement: "bottom",
  },
  {
    id: "visibility-chart",
    path: "/dashboard",
    targetId: "overview-visibility-chart",
    eyebrow: "Trend",
    title: "See whether your brand is gaining ground",
    body: "This chart compares your visibility against competitors over time so movement is visible instead of buried in raw answers.",
    placement: "right",
  },
  {
    id: "brands",
    path: "/dashboard",
    targetId: "overview-brands-table",
    eyebrow: "Competition",
    title: "Know who AI engines prefer",
    body: "The brand table shows which companies are winning AI recommendations, their sentiment, and their average answer position.",
    placement: "left",
  },
  {
    id: "sources",
    path: "/dashboard",
    targetId: "overview-sources",
    eyebrow: "Citations",
    title: "Find the sources shaping AI answers",
    body: "Sources show which domains influence AI responses. This is the evidence layer behind GEO strategy and content priorities.",
    placement: "top",
  },
  {
    id: "chats",
    path: "/dashboard",
    targetId: "overview-recent-chats",
    eyebrow: "Evidence",
    title: "Open the exact AI answers behind the numbers",
    body: "Recent Chats are saved answer snapshots. Use them to inspect prompt wording, mentioned brands, citations, and response context.",
    placement: "top",
  },
  {
    id: "prompts-intro",
    path: "/prompts",
    targetId: "prompts-shell",
    eyebrow: "Prompts",
    title: "Prompts are the buyer questions we track",
    body: "This tab contains the real user-style questions we run across AI engines. Each row shows whether your brand appears, which brands are mentioned, and how strong the result is.",
    placement: "bottom",
  },
  {
    id: "prompts-topics",
    path: "/prompts",
    targetId: "prompts-topics",
    eyebrow: "Topics",
    title: "Organize tracking by intent",
    body: "Topics group prompts by buyer intent such as alternatives, comparisons, pricing, or category research. This keeps reporting and filters clean as the account grows.",
    placement: "right",
  },
  {
    id: "prompts-controls",
    path: "/prompts",
    targetId: "prompts-controls",
    eyebrow: "Prompt Controls",
    title: "Approve, discover, and add prompts",
    body: "Suggested prompts are not blindly tracked. Review them first, discover new prompt ideas from existing evidence, or add a specific query your team cares about.",
    placement: "bottom",
  },
  {
    id: "prompts-table",
    path: "/prompts",
    targetId: "prompts-table",
    eyebrow: "Prompt Evidence",
    title: "Each row is a tracked AI-search demand signal",
    body: "Visibility shows if you appear, sentiment shows tone, position shows rank, mentions show competitors, and volume gives a directional priority signal.",
    placement: "top",
  },
  {
    id: "sources-overview",
    path: "/sources",
    targetId: "sources-overview",
    eyebrow: "Sources",
    title: "Sources explain why AI answers happen",
    body: "This is the citation layer. It shows which domains and page types influence answers, so GEO work is based on evidence instead of guessing.",
    placement: "bottom",
  },
  {
    id: "sources-table",
    path: "/sources",
    targetId: "sources-table",
    eyebrow: "Source Tables",
    title: "Move from domains to exact URLs",
    body: "Start with domains, switch to URLs, or open Brand gaps to find pages where competitors are cited but your brand is missing.",
    placement: "top",
  },
  {
    id: "competitors",
    path: "/competitors",
    targetId: "competitors-shell",
    eyebrow: "Competitors",
    title: "Track who AI engines prefer",
    body: "Competitors can be manually tracked or discovered from AI answers. Once tracked, they appear in Overview, prompts, reports, and gap analysis.",
    placement: "bottom",
  },
  {
    id: "opportunities",
    path: "/opportunities",
    targetId: "opportunities-shell",
    eyebrow: "Opportunities",
    title: "Turn evidence into a prioritized backlog",
    body: "This page ranks content and source gaps by impact. It tells teams what to create, refresh, or investigate first instead of handing them raw analytics.",
    placement: "bottom",
  },
  {
    id: "ai-workspace",
    path: "/ai-workspace",
    targetId: "ai-workspace-shell",
    eyebrow: "AI Workspace",
    title: "Turn intelligence into finished work",
    body: "Reports and content briefs live here. This is where source evidence, prompt gaps, and competitor insights become client-ready strategy and content.",
    placement: "bottom",
  },
  {
    id: "chat",
    path: "/chat",
    targetId: "chat-history-shell",
    eyebrow: "Chat Evidence",
    title: "Open the saved answers behind every metric",
    body: "Chat history is the audit trail. Use it to inspect prompts, model answers, brands, citations, and exact response context when a number needs proof.",
    placement: "bottom",
  },
  {
    id: "finish",
    path: "/dashboard",
    targetId: "nav-help",
    eyebrow: "You are set",
    title: "Skip anytime, come back through Help",
    body: "You now know the core flow: track prompts, inspect sources, compare competitors, then ship improvements from the workspace.",
    placement: "right",
  },
]
